// Vue/src/components/ListFiltered.vue
<script setup lang="ts">
import { ProjectList } from '../interfaces/interfaces';
import { computed} from 'vue'
const props = defineProps<{ data: ProjectList[] }>();
const filteredProjects = computed(() => props.data);
</script>

<template>
    <li
        v-for="{ nombrePresupuesto, cliente, presupuesto, fullPath }, index in filteredProjects"
        :key="index"
        class="mb-2"
    >
        <p>
            <strong>Cliente:</strong>
            {{ cliente }}
        </p>
                <p>
                    <strong>Nombre del Presupuesto: </strong>
                    <router-link
                        :to="fullPath"
                        target="_blank"
                        class="text-orange-500 underline"
                    >{{ nombrePresupuesto }}</router-link>
                </p>
        <p>
            <strong>Precio:</strong>
            {{ presupuesto }}
        </p>
        <hr class="mt-2 border-slate-500" />
    </li>
</template>

<style scoped>
</style>

// SvelteKit/src/components/ListFiltered.svelte
<script lang="ts">
	import type { ProjectList } from '../../src/interfaces/interfaces';
	export let filteredProjects: ProjectList[] = [];
</script>

{#each filteredProjects as { nombrePresupuesto, cliente, totalConPaginas, fullPath, id } (id)}
	<li class="mb-2">
		<p>
			<strong>Cliente: </strong>
			{cliente}
		</p>
		<p>
			<strong>Nombre del Presupuesto: </strong>
			<a href={fullPath} target="_blank" class="text-orange-500 underline"> {nombrePresupuesto}</a>
		</p>
		<p>
			<strong>Precio:</strong>
			{totalConPaginas}
		</p>
		<hr class="mt-2 border-slate-500" />
	</li>
{/each}
